# Generated by Django 5.1.5 on 2025-01-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_remove_coffeeproduct_measurement_grams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeproduct',
            name='measurement_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
