# Generated by Django 5.1.5 on 2025-02-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_coffeeproduct_measurement_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
