# Generated by Django 5.1.5 on 2025-02-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_alter_coffeeproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coffeeproduct',
            name='name',
        ),
    ]
