# Generated by Django 5.1.5 on 2025-02-15 09:49

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_remove_coffeeproduct_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
